# backend/pipelines/methods_text.py
"""Reusable methods text generators for pipeline stages.

Each function produces manuscript-ready text describing the exact tools,
versions, and parameters used — suitable for copy-paste into a Methods section.
"""

# Correct per-genome effective genome sizes (cleave-spec-decisions.md §7)
EFFECTIVE_GENOME_SIZES = {
    "mm10": 2_467_481_108,
    "hg38": 2_913_022_398,
    "hg19": 2_864_785_220,
    "dm6": 142_573_017,
    "sacCer3": 12_157_105,
}

# Human-readable genome names for methods text
GENOME_DISPLAY_NAMES = {
    "mm10": "Mouse mm10",
    "hg38": "Human GRCh38/hg38",
    "hg19": "Human hg19",
    "dm6": "Drosophila dm6",
    "sacCer3": "Yeast sacCer3",
}


def peak_calling_methods(params: dict) -> str:
    """Generate peak calling methods text matching CUTANA Cloud format.

    Reference: cutana/H3K4me3/methods.txt
    """
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    peak_caller = params.get("peak_caller", "MACS2")
    peak_size = params.get("peak_size", "narrow")
    q_value = params.get("q_value", 0.01)
    fragment_filter = params.get("fragment_filter", True)
    broad_cutoff = params.get("broad_cutoff", 0.1)

    text = (
        f"Peaks were called on the {genome_display} reference genome "
        f"using the Cleave Peak Calling Pipeline. "
    )

    if fragment_filter:
        frag_size = params.get("fragment_size", 120)
        text += (
            f"BAM files were filtered to retain only sub-nucleosomal fragments "
            f"(< {frag_size} bp) prior to peak calling. "
        )

    if peak_caller == "MACS2":
        text += (
            f"BED files were produced by MACS2 (version 2.2.9.1) "
            f"in {peak_size} mode with an automatically determined bin size "
            f"based on each input file and a significance threshold "
        )
        if peak_size == "broad":
            text += f"(broad-cutoff) of {broad_cutoff}. "
        else:
            text += f"(q-value) of {q_value}. "
    elif peak_caller == "SEACR":
        seacr_threshold = params.get("seacr_threshold", 0.01)
        text += (
            f"Peaks were called using SEACR (version 1.1) in {peak_size} mode "
            f"with a threshold of {seacr_threshold}. "
            f"Bedgraph files were generated by MACS2 and converted to integer format "
            f"prior to SEACR analysis. "
        )
    elif peak_caller == "SICER2":
        sicer2_fdr = params.get("sicer2_fdr", 0.01)
        sicer2_window = params.get("sicer2_window", 200)
        sicer2_gap = params.get("sicer2_gap", 600)
        text += (
            f"Peaks were called using SICER2 with a window size of "
            f"{sicer2_window} bp, gap size of {sicer2_gap} bp, "
            f"and FDR threshold of {sicer2_fdr}. "
        )

    text += (
        "FRiP scores were calculated by dividing the number of reads in peaks "
        "(determined by BEDTools) by the total number of reads "
        "(determined by SAMtools). "
        "Peak annotation was performed by HOMER."
    )

    return text


def diffbind_methods(params: dict) -> str:
    """Generate DiffBind methods text for the differential peak analysis pipeline."""
    method = params.get("analysis_method", "deseq2_consensus")
    samples = params.get("samples", [])
    n_samples = len(samples)
    conditions = sorted({s["condition"] for s in samples})

    engine = "DESeq2" if "deseq2" in method else "edgeR"
    if "consensus" in method:
        peakset_desc = "A consensus peakset was derived from overlapping peaks across all samples"
    else:
        peakset_desc = "A user-supplied custom peakset was used for read counting"

    norm_desc = ""
    if method == "edger_peaklist":
        norm_desc = (
            "Reads were normalized using the TMM (trimmed mean of M-values) method "
            "with full library sizes and native normalization. "
        )

    return (
        f"Differential peak analysis was performed using DiffBind with {engine} "
        f"as the statistical engine. "
        f"{peakset_desc} across {n_samples} samples in {len(conditions)} conditions "
        f"({', '.join(conditions)}). "
        f"{norm_desc}"
        f"Contrasts were computed between conditions with a minimum of 2 replicates "
        f"per group. Differentially bound sites were identified and reported with "
        f"log2 fold changes and FDR-adjusted p-values for all peaks (threshold = 1). "
        f"PCA plots, correlation heatmaps, MA plots, and volcano plots were generated "
        f"for quality assessment."
    )


def alignment_methods(params: dict) -> str:
    """Generate alignment methods text matching CUTANA Cloud format.

    Reference: cutana/H3K4me3/methods.txt
    """
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    remove_dups = params.get("remove_duplicates", True)
    remove_dac = params.get("remove_dac_exclusion", True)
    bin_size = params.get("bam_coverage_bin_size", 20)
    smoothed_bin_size = params.get("smoothed_bin_size", 100)
    eff_size = EFFECTIVE_GENOME_SIZES.get(genome, 0)

    text = (
        f"Paired-end reads were aligned to the {genome_display} reference genome "
        f"using Bowtie2 (--dovetail --phred33). "
        f"Multi-aligned reads (MAPQ < 10) were removed using SAMtools. "
    )
    if remove_dac:
        text += "Reads mapping to ENCODE DAC Exclusion List regions were removed using BEDTools. "
    if remove_dups:
        text += "Duplicate reads were identified with Picard MarkDuplicates and removed. "
    text += (
        f"RPKM-normalized bigWig files were generated via deepTools bamCoverage "
        f"(--binSize {bin_size}, effectiveGenomeSize {eff_size}). "
        f"Smoothed bigWig files were generated with --binSize {smoothed_bin_size} "
        f"for IGV visualization. "
        f"Enrichment at transcription start sites (reference-point mode) and "
        f"annotated gene bodies (scale-regions mode) was computed using deepTools "
        f"computeMatrix and visualized with plotHeatmap."
    )
    return text


def custom_heatmap_methods(params: dict) -> str:
    """Generate methods text for custom reference-point heatmaps.

    Reference: references/genomewide_plots/heatmaps.sh
    """
    samples = params.get("samples", [])
    n_samples = len(samples)
    bed_label = params.get("bed_label", "user-provided regions")
    upstream = params.get("flanking_upstream", 1500)
    downstream = params.get("flanking_downstream", 1500)
    ref_point = params.get("reference_point", "center")
    sort_order = params.get("sort_order", "descend")
    color_map = params.get("color_map") or None

    text = (
        f"Custom reference-point heatmaps were generated using deepTools. "
        f"Signal from RPKM-normalized bigWig files for {n_samples} sample"
        f"{'s' if n_samples != 1 else ''} was computed around the "
        f"{ref_point} of regions in the reference BED file "
        f"({bed_label}) with a flanking window of {upstream} bp upstream "
        f"and {downstream} bp downstream using computeMatrix reference-point. "
        f"Heatmaps were visualized using plotHeatmap "
        f"and mean signal profiles were generated using plotProfile (--perGroup)"
    )

    extras: list[str] = []
    if sort_order != "descend":
        extras.append(f"--sortRegions {sort_order}")
    if color_map:
        extras.append(f"--colorMap {color_map}")
    if extras:
        text += f" ({', '.join(extras)})"

    text += "."
    return text
