# backend/pipelines/methods_text.py
"""Reusable methods text generators for pipeline stages.

Each function produces manuscript-ready text describing the exact tools,
versions, and parameters used — suitable for copy-paste into a Methods section.
"""

# Correct per-genome effective genome sizes (cleave-spec-decisions.md §7)
EFFECTIVE_GENOME_SIZES = {
    "mm10": 2_467_481_108,
    "hg38": 2_913_022_398,
    "hg19": 2_864_785_220,
    "dm6": 142_573_017,
    "sacCer3": 12_157_105,
}

# Human-readable genome names for methods text
GENOME_DISPLAY_NAMES = {
    "mm10": "Mouse mm10",
    "hg38": "Human GRCh38/hg38",
    "hg19": "Human hg19",
    "dm6": "Drosophila dm6",
    "sacCer3": "Yeast sacCer3",
}

# TODO(genome-versions): RNA-seq annotation versions for auto-generated methods text.
# When updating genome annotations, change BOTH this dict AND the matching
# "gtf_filename" in rnaseq_alignment.RNASEQ_GENOME_CONFIG.
# Current: mouse gencode.vM10, human gencode.v29 (from lab reference scripts).
RNASEQ_ANNOTATION_VERSIONS = {
    "mm10": "GENCODE vM10",  # TODO(genome-versions): e.g., "GENCODE vM35"
    "hg38": "GENCODE v29",  # TODO(genome-versions): e.g., "GENCODE v46"
}


def peak_calling_methods(params: dict) -> str:
    """Generate peak calling methods text matching CUTANA Cloud format.

    Reference: cutana/H3K4me3/methods.txt
    """
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    peak_caller = params.get("peak_caller", "MACS2")
    peak_size = params.get("peak_size", "narrow")
    q_value = params.get("q_value", 0.01)
    fragment_filter = params.get("fragment_filter", True)
    broad_cutoff = params.get("broad_cutoff", 0.1)

    text = (
        f"Peaks were called on the {genome_display} reference genome "
        f"using the Cleave Peak Calling Pipeline. "
    )

    if fragment_filter:
        frag_size = params.get("fragment_size", 120)
        text += (
            f"BAM files were filtered to retain only sub-nucleosomal fragments "
            f"(< {frag_size} bp) prior to peak calling. "
        )

    if peak_caller == "MACS2":
        text += (
            f"BED files were produced by MACS2 (version 2.2.9.1) "
            f"in {peak_size} mode with an automatically determined bin size "
            f"based on each input file and a significance threshold "
        )
        if peak_size == "broad":
            text += f"(broad-cutoff) of {broad_cutoff}. "
        else:
            text += f"(q-value) of {q_value}. "
    elif peak_caller == "SEACR":
        seacr_threshold = params.get("seacr_threshold", 0.01)
        text += (
            f"Peaks were called using SEACR (version 1.1) in {peak_size} mode "
            f"with a threshold of {seacr_threshold}. "
            f"Bedgraph files were generated by MACS2 and converted to integer format "
            f"prior to SEACR analysis. "
        )
    elif peak_caller == "SICER2":
        sicer2_fdr = params.get("sicer2_fdr", 0.01)
        sicer2_window = params.get("sicer2_window", 200)
        sicer2_gap = params.get("sicer2_gap", 600)
        text += (
            f"Peaks were called using SICER2 with a window size of "
            f"{sicer2_window} bp, gap size of {sicer2_gap} bp, "
            f"and FDR threshold of {sicer2_fdr}. "
        )

    blacklist_type = params.get("blacklist", "encode_dac")
    if blacklist_type == "encode_dac":
        text += "Peaks overlapping ENCODE DAC Exclusion List regions were removed. "
    elif blacklist_type == "lab_custom":
        text += "Peaks overlapping lab-curated blacklist regions were removed. "
    elif blacklist_type == "both":
        text += (
            "Peaks overlapping ENCODE DAC Exclusion List regions and "
            "lab-curated blacklist regions were removed. "
        )

    text += (
        "FRiP scores were calculated by dividing the number of reads in peaks "
        "(determined by BEDTools) by the total number of reads "
        "(determined by SAMtools). "
        "Peak annotation was performed by HOMER."
    )

    return text


def diffbind_methods(params: dict) -> str:
    """Generate DiffBind methods text for the differential peak analysis pipeline."""
    method = params.get("analysis_method", "deseq2_consensus")
    samples = params.get("samples", [])
    n_samples = len(samples)
    conditions = sorted({s["condition"] for s in samples})

    engine = "DESeq2" if "deseq2" in method else "edgeR"
    if "consensus" in method:
        peakset_desc = "A consensus peakset was derived from overlapping peaks across all samples"
    else:
        peakset_desc = "A user-supplied custom peakset was used for read counting"

    norm_desc = ""
    if method == "edger_peaklist":
        norm_desc = (
            "Reads were normalized using the TMM (trimmed mean of M-values) method "
            "with full library sizes and native normalization. "
        )

    return (
        f"Differential peak analysis was performed using DiffBind with {engine} "
        f"as the statistical engine. "
        f"{peakset_desc} across {n_samples} samples in {len(conditions)} conditions "
        f"({', '.join(conditions)}). "
        f"{norm_desc}"
        f"Contrasts were computed between conditions with a minimum of 2 replicates "
        f"per group. Differentially bound sites were identified and reported with "
        f"log2 fold changes and FDR-adjusted p-values for all peaks (threshold = 1). "
        f"PCA plots, correlation heatmaps, MA plots, and volcano plots were generated "
        f"for quality assessment."
    )


def alignment_methods(params: dict) -> str:
    """Generate alignment methods text matching CUTANA Cloud format.

    Reference: cutana/H3K4me3/methods.txt
    """
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    remove_dups = params.get("remove_duplicates", True)
    remove_dac = params.get("remove_dac_exclusion", True)
    bin_size = params.get("bam_coverage_bin_size", 20)
    smoothed_bin_size = params.get("smoothed_bin_size", 100)
    eff_size = EFFECTIVE_GENOME_SIZES.get(genome, 0)

    text = (
        f"Paired-end reads were aligned to the {genome_display} reference genome "
        f"using Bowtie2 (--dovetail --phred33). "
        f"Multi-aligned reads (MAPQ < 10) were removed using SAMtools. "
    )
    if remove_dac:
        text += "Reads mapping to ENCODE DAC Exclusion List regions were removed using BEDTools. "
    if remove_dups:
        text += "Duplicate reads were identified with Picard MarkDuplicates and removed. "
    text += (
        f"RPKM-normalized bigWig files were generated via deepTools bamCoverage "
        f"(--binSize {bin_size}, effectiveGenomeSize {eff_size}). "
        f"Smoothed bigWig files were generated with --binSize {smoothed_bin_size} "
        f"for IGV visualization. "
        f"Enrichment at transcription start sites (reference-point mode) and "
        f"annotated gene bodies (scale-regions mode) was computed using deepTools "
        f"computeMatrix and visualized with plotHeatmap."
    )
    return text


def custom_heatmap_methods(params: dict) -> str:
    """Generate methods text for custom reference-point heatmaps.

    Reference: references/genomewide_plots/heatmaps.sh
    """
    samples = params.get("samples", [])
    n_samples = len(samples)
    bed_label = params.get("bed_label", "user-provided regions")
    upstream = params.get("flanking_upstream", 1500)
    downstream = params.get("flanking_downstream", 1500)
    ref_point = params.get("reference_point", "center")
    sort_order = params.get("sort_order", "descend")
    color_map = params.get("color_map") or None

    text = (
        f"Custom reference-point heatmaps were generated using deepTools. "
        f"Signal from RPKM-normalized bigWig files for {n_samples} sample"
        f"{'s' if n_samples != 1 else ''} was computed around the "
        f"{ref_point} of regions in the reference BED file "
        f"({bed_label}) with a flanking window of {upstream} bp upstream "
        f"and {downstream} bp downstream using computeMatrix reference-point. "
        f"Heatmaps were visualized using plotHeatmap "
        f"and mean signal profiles were generated using plotProfile (--perGroup)"
    )

    extras: list[str] = []
    if sort_order != "descend":
        extras.append(f"--sortRegions {sort_order}")
    if color_map:
        extras.append(f"--colorMap {color_map}")
    if extras:
        text += f" ({', '.join(extras)})"

    text += "."
    return text


def pearson_correlation_methods(params: dict) -> str:
    """Generate methods text for Pearson correlation analysis.

    Reference: references/media_pearson_corr/peak_extractor.r + pearson.py
    """
    samples = params.get("samples", [])
    n_samples = len(samples)
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    masking = genome == "mm10"
    restrict_bed = params.get("restrict_bed_path")
    bed_label = params.get("restrict_bed_label", "user-provided regions")

    resolution = params.get("bigwig_resolution", 50)

    text = (
        f"Pairwise Pearson correlation analysis was performed to assess "
        f"replicate concordance across {n_samples} sample"
        f"{'s' if n_samples != 1 else ''}. "
        f"RPKM-normalized bigWig signal was extracted at {resolution} bp resolution "
        f"across all autosomes and chrX of the {genome_display} reference "
        f"genome using rtracklayer (R). "
        f"Genomic bins with zero coverage across all samples were removed. "
    )

    if masking:
        text += (
            "Manually curated masked regions (158 entries) were excluded "
            "to remove loci with artificially high or low signal. "
        )

    if restrict_bed:
        text += f"Signal was restricted to bins overlapping regions in {bed_label}. "

    text += (
        "Pairwise Pearson correlation coefficients were computed using "
        "pandas DataFrame.corr() and visualized as an annotated heatmap "
        "using seaborn (cmap='Blues', 2 decimal places)."
    )

    return text


def rnaseq_alignment_methods(params: dict) -> str:
    """Generate RNA-seq alignment methods text for manuscripts.

    Reference: references/archival/rnaseq/mouse/align_reads.sh (STAR),
               references/archival/rnaseq/mouse/salmon_quant2.sh (Salmon),
               references/archival/rnaseq/mouse/create_bw.sh (bamCoverage)
    """
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    bin_size = params.get("bam_coverage_bin_size", 20)
    smoothed_bin_size = params.get("smoothed_bin_size", 100)
    eff_size = EFFECTIVE_GENOME_SIZES.get(genome, 0)
    remove_dups = params.get("remove_duplicates", False)

    annotation_ver = RNASEQ_ANNOTATION_VERSIONS.get(genome, "")
    annotation_note = f" ({annotation_ver})" if annotation_ver else ""

    text = (
        f"Paired-end RNA-seq reads were aligned to the {genome_display} reference genome"
        f"{annotation_note} using STAR "
        f"(--outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM "
        f"--readFilesCommand zcat). "
    )
    if remove_dups:
        text += "Duplicate reads were removed using SAMtools (-F 1024). "
    text += (
        f"Transcript-level quantification was performed using Salmon "
        f"(--libType A --gcBias --validateMappings) with automatic library type detection. "
        f"RPKM-normalized bigWig files were generated via deepTools bamCoverage "
        f"(--binSize {bin_size}, effectiveGenomeSize {eff_size:,}). "
        f"Smoothed bigWig files were generated with --binSize {smoothed_bin_size} "
        f"for genome browser visualization."
    )
    return text


def rnaseq_feature_counts_methods(params: dict) -> str:
    """Generate featureCounts methods text for manuscripts."""
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    strandedness = params.get("strandedness", 0)
    reactions = params.get("reactions", [])
    n_samples = len(reactions)

    annotation_ver = RNASEQ_ANNOTATION_VERSIONS.get(genome, "")
    annotation_note = f" ({annotation_ver})" if annotation_ver else ""

    strand_desc = {0: "unstranded", 1: "forward-stranded", 2: "reverse-stranded"}.get(
        strandedness, "unstranded"
    )

    return (
        f"Gene-level read counts were generated from coordinate-sorted BAMs using "
        f"featureCounts (Subread package) with the {genome_display} "
        f"annotation{annotation_note}. "
        f"Paired-end reads were counted using fragment-level assignment "
        f"(-p --countReadPairs) in {strand_desc} mode (-s {strandedness}) "
        f"with primary alignments only (--primary). "
        f"{n_samples} sample{'s' if n_samples != 1 else ''} "
        f"{'were' if n_samples != 1 else 'was'} quantified in a single invocation "
        f"producing a combined gene-by-sample count matrix."
    )


def rnaseq_de_methods(params: dict) -> str:
    """Generate DESeq2 differential expression methods text for manuscripts."""
    genome = params.get("reference_genome", "unknown")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    source = params.get("quantification_source", "salmon")
    samples = params.get("samples", [])
    conditions = sorted(set(s.get("condition", "") for s in samples))
    reference_condition = params.get("reference_condition")

    annotation_ver = RNASEQ_ANNOTATION_VERSIONS.get(genome, "")
    annotation_note = f" ({annotation_ver})" if annotation_ver else ""

    text = "Differential expression analysis was performed using DESeq2 (Love et al., 2014). "

    if source == "salmon":
        text += (
            "Transcript-level abundance estimates from Salmon were imported "
            "to gene-level counts using tximport (Soneson et al., 2015). "
        )
    elif source == "featurecounts":
        text += (
            "Gene-level read counts from featureCounts (Subread package) were used "
            "as input for differential expression analysis. "
        )

    text += (
        f"The design formula ~condition was used to test for differential "
        f"expression between {' and '.join(conditions)}"
    )
    if reference_condition:
        text += f" with {reference_condition} as the reference level"
    text += ". "

    text += (
        f"Genes with an adjusted p-value (Benjamini-Hochberg) < 0.05 were "
        f"considered significantly differentially expressed. "
        f"Reference genome: {genome_display}{annotation_note}."
    )
    return text


def rnaseq_trimming_methods(params: dict) -> str:
    """Generate fastp trimming methods text for manuscripts."""
    phred = params.get("qualified_quality_phred", 20)
    min_len = params.get("length_required", 25)
    win_size = params.get("cut_window_size", 4)
    win_qual = params.get("cut_mean_quality", 15)

    return (
        f"Adapter sequences were detected and removed using fastp "
        f"(--detect_adapter_for_pe) with quality filtering "
        f"(qualified_quality_phred {phred}, length_required {min_len}). "
        f"Sliding window trimming was applied from both ends "
        f"(window size {win_size}, mean quality {win_qual})."
    )


def rnaseq_qc_methods(params: dict) -> str:
    """Generate RSeQC + MultiQC QC methods text for manuscripts."""
    genome = params.get("reference_genome", "mm10")
    genome_display = GENOME_DISPLAY_NAMES.get(genome, genome)
    reactions = params.get("reactions", [])
    n_samples = len(reactions)

    annotation_ver = RNASEQ_ANNOTATION_VERSIONS.get(genome, "")
    annotation_note = f" ({annotation_ver})" if annotation_ver else ""

    return (
        f"RNA-seq quality control was performed on {n_samples} "
        f"sample{'s' if n_samples != 1 else ''} using RSeQC against the "
        f"{genome_display} gene model{annotation_note}. "
        f"Strandedness was inferred using infer_experiment.py. "
        f"Read distribution across genomic features (CDS, UTR, intron, intergenic) "
        f"was assessed by read_distribution.py. "
        f"Gene body coverage uniformity, insert size distribution, and splice "
        f"junction saturation were evaluated using geneBody_coverage.py, "
        f"inner_distance.py, and junction_saturation.py, respectively. "
        f"Results from RSeQC, STAR, Salmon, and fastp were aggregated into "
        f"an interactive report using MultiQC."
    )


def roman_normalization_methods(params: dict) -> str:
    """Generate methods text for Roman normalization."""
    samples = params.get("samples", [])
    n_samples = len(samples)
    first_label = (
        samples[0].get("label", samples[0].get("short_name", "first sample"))
        if samples
        else "first sample"
    )

    text = (
        f"Sample-to-sample normalization was performed using 99th-percentile "
        f"quantile normalization (Roman normalization). RPKM-normalized "
        f"bigWig signal was extracted at 50 bp resolution across mouse "
        f"autosomes (chr1\u201319) and chrX of the "
        f"{GENOME_DISPLAY_NAMES.get('mm10', 'Mouse mm10')} reference genome "
        f"using rtracklayer (R). Genomic bins with zero coverage across all "
        f"{n_samples} sample{'s' if n_samples != 1 else ''} were removed. "
        f"Manually curated masked regions (158 entries) were excluded to "
        f"eliminate loci with artificially extreme signal. The 99th percentile "
        f"of signal intensity was computed for each sample from the filtered "
        f"coverage matrix. Normalization factors were calculated by dividing "
        f"each sample\u2019s 99th percentile by that of the reference sample "
        f"({first_label}). Original bigWig scores were divided by the "
        f"corresponding normalization factor and rounded to two decimal "
        f"places. Normalized bigWig files (*_rnorm.bw) were exported for "
        f"downstream visualization."
    )

    return text
