"""add termination and retry columns

Revision ID: 19f7810a826a
Revises: 4f02b80e7f9b
Create Date: 2026-03-29 00:52:52.497077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f7810a826a'
down_revision: Union[str, None] = '4f02b80e7f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('termination_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('analysis_jobs', sa.Column('retry_of_job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'analysis_jobs', 'analysis_jobs', ['retry_of_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_jobs', type_='foreignkey')
    op.drop_column('analysis_jobs', 'retry_of_job_id')
    op.drop_column('analysis_jobs', 'termination_requested_at')
    # ### end Alembic commands ###
