"""add auto pipeline columns

Revision ID: 1b988efe774f
Revises: ddf72d64a676
Create Date: 2026-03-29 08:30:33.657027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b988efe774f'
down_revision: Union[str, None] = 'ddf72d64a676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('auto_pipeline', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('experiments', sa.Column('auto_pipeline', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('experiments', sa.Column('auto_pipeline_status', sa.String(), nullable=True))
    op.add_column('experiments', sa.Column('auto_pipeline_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'auto_pipeline_config')
    op.drop_column('experiments', 'auto_pipeline_status')
    op.drop_column('experiments', 'auto_pipeline')
    op.drop_column('analysis_jobs', 'auto_pipeline')
    # ### end Alembic commands ###
