"""add_fastqc_report_path

Revision ID: 35ad430891c0
Revises: fafd5c9dc468
Create Date: 2026-03-25 17:46:31.288408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ad430891c0'
down_revision: Union[str, None] = 'fafd5c9dc468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastq_files', sa.Column('fastqc_report_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fastq_files', 'fastqc_report_path')
    # ### end Alembic commands ###
