"""add_adapter_status

Revision ID: 87e85de24803
Revises: 35ad430891c0
Create Date: 2026-03-26 06:04:53.140517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e85de24803'
down_revision: Union[str, None] = '35ad430891c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastq_files', sa.Column('adapter_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fastq_files', 'adapter_status')
    # ### end Alembic commands ###
