"""add password_changed_at to users

Revision ID: ddf72d64a676
Revises: 19f7810a826a
Create Date: 2026-03-29 03:51:25.538198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf72d64a676'
down_revision: Union[str, None] = '19f7810a826a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    # ### end Alembic commands ###
