// frontend/src/lib/constants.ts

export const STATUS_COLORS: Record<string, string> = {
  new: 'bg-status-new',
  in_progress: 'bg-status-in-progress',
  complete: 'bg-status-complete',
  error: 'bg-status-error',
  terminated: 'bg-status-terminated',
  queued: 'bg-status-new',
  running: 'bg-status-in-progress',
};

export const STATUS_LABELS: Record<string, string> = {
  new: 'New',
  in_progress: 'In Progress',
  complete: 'Complete',
  error: 'Error',
  terminated: 'Terminated',
  queued: 'Queued',
  running: 'Running',
};

export const ROLE_LABELS: Record<string, string> = {
  admin: 'Admin',
  contributor: 'Contributor',
  viewer: 'Viewer',
};

export const EMAIL_NOTIFICATION_OPTIONS = [
  { value: 'always', label: 'Always' },
  { value: 'on_error', label: 'On Error' },
  { value: 'never', label: 'Never' },
] as const;

export const ASSAY_TYPES = ['CUT&RUN', 'CUT&Tag', 'RNA-seq'] as const;

export const ORGANISMS = ['Human', 'Mouse', 'Drosophila', 'Yeast'] as const;

export const CUTANA_SPIKE_IN_OPTIONS = ['None', 'KMetStat'] as const;

export const REFERENCE_GENOMES: Record<string, { value: string; label: string }[]> = {
  Human: [
    { value: 'hg38', label: 'Human GRCh38/hg38' },
    { value: 'hg19', label: 'Human hg19' },
  ],
  Mouse: [{ value: 'mm10', label: 'Mouse mm10' }],
  Drosophila: [{ value: 'dm6', label: 'Drosophila dm6' }],
  Yeast: [{ value: 'sacCer3', label: 'Yeast sacCer3' }],
};

export const GENOME_DISPLAY_NAMES: Record<string, string> = {
  mm10: 'Mouse mm10',
  hg38: 'Human GRCh38/hg38',
  hg19: 'Human hg19',
  dm6: 'Drosophila dm6',
  sacCer3: 'Yeast sacCer3',
};

export const ALIGNMENT_FILE_CATEGORIES = [
  {
    value: 'unique_bam',
    label: 'Unique BAM',
    description:
      'A BAM file is a compressed output from Alignment representing each sequencing read and where they align to the reference genome. The Unique BAM is the final version that has been filtered for reads that align to multiple locations on the genome, are duplicates, or map to DAC Exclusion List Regions.',
  },
  {
    value: 'bigwig',
    label: 'bigWig',
    description:
      'RPKM-normalized signal tracks with binsize 20, used for precise heatmap generation without artificial smoothing.',
  },
  {
    value: 'smoothed_bigwig',
    label: 'smoothed bigWig',
    description:
      'Smoothed RPKM-normalized signal tracks with binsize 100, optimized for visual clarity when exploring data in IGV.',
  },
  {
    value: 'tss_heatmap',
    label: 'TSS Heatmaps',
    description:
      'Heatmap images showing enrichment of unique reads around transcription start sites, generated by deepTools plotHeatmap.',
  },
  {
    value: 'genebody_heatmap',
    label: 'Gene Body Heatmaps',
    description:
      'Heatmap images showing enrichment of unique reads across scaled gene bodies, generated by deepTools plotHeatmap.',
  },
  {
    value: 'log',
    label: 'Logs',
    description:
      'Pipeline execution log files including Bowtie2 alignment logs and Picard duplicate marking metrics.',
  },
] as const;

export const PEAK_CALLERS = [
  { value: 'MACS2', label: 'MACS2' },
  { value: 'SICER2', label: 'SICER2' },
  { value: 'SEACR', label: 'SEACR' },
] as const;

export const PEAK_SIZES: Record<string, { value: string; label: string }[]> = {
  MACS2: [
    { value: 'narrow', label: 'Narrow' },
    { value: 'broad', label: 'Broad' },
  ],
  SICER2: [{ value: 'broad', label: 'Broad' }],
  SEACR: [
    { value: 'stringent', label: 'Stringent' },
    { value: 'relaxed', label: 'Relaxed' },
  ],
};

export const PEAK_CALLING_FILE_CATEGORIES = [
  {
    value: 'bed',
    label: 'BED Files',
    description:
      'Peak coordinate files in BED format defining genomic regions where target signal is significantly enriched over background.',
  },
  {
    value: 'frip',
    label: 'FRiP Score',
    description:
      'Fraction of Reads in Peaks metrics — the ratio of unique reads associated with statistically significant peaks to total reads.',
  },
  {
    value: 'annotation',
    label: 'Peak Annotation',
    description:
      'HOMER peak annotation output files mapping each peak to the nearest genomic feature (promoter, exon, intron, intergenic, etc.).',
  },
  {
    value: 'annotation_stats',
    label: 'Peak Annotation Stats',
    description: 'Summary statistics from HOMER annotation showing the distribution of peaks across genomic features.',
  },
  {
    value: 'log',
    label: 'Logs',
    description: 'Peak calling pipeline execution log files.',
  },
] as const;

export const BLACKLIST_OPTIONS = [
  { value: 'encode_dac', label: 'ENCODE DAC Exclusion List' },
  { value: 'lab_custom', label: 'Lab Custom Blacklist (mm10)' },
  { value: 'both', label: 'Both (ENCODE DAC + Lab Custom)' },
  { value: 'none', label: 'None' },
] as const;

export const PEAK_CALLING_DEFAULTS: {
  q_value: number;
  broad_cutoff: number;
  seacr_threshold: number;
  sicer2_fdr: number;
  fragment_filter: boolean;
  fragment_size: number;
  blacklist: string;
} = {
  q_value: 0.01,
  broad_cutoff: 0.1,
  seacr_threshold: 0.01,
  sicer2_fdr: 0.01,
  fragment_filter: true,
  fragment_size: 120,
  blacklist: 'both',
};

export const DIFFBIND_ANALYSIS_METHODS = [
  { value: 'deseq2_consensus', label: 'DESeq2 (Consensus Peakset)' },
  { value: 'deseq2_peaklist', label: 'DESeq2 (Custom Peakset)' },
  { value: 'edger_peaklist', label: 'edgeR (Custom Peakset)' },
] as const;

export const DIFFBIND_FILE_CATEGORIES = [
  {
    value: 'diffbind_results',
    label: 'Results',
    description: 'Differential binding results with fold change, p-values, and FDR.',
  },
  {
    value: 'normalized_counts',
    label: 'Normalized Counts',
    description: 'Read counts matrix normalized across all samples.',
  },
  {
    value: 'diffbind_plot_pca',
    label: 'PCA Plot',
    description: 'Principal Component Analysis of sample similarity.',
  },
  {
    value: 'diffbind_plot_ma',
    label: 'MA Plot',
    description: 'Mean-Average plot showing fold change vs. mean concentration.',
  },
  {
    value: 'diffbind_plot_volcano',
    label: 'Volcano Plot',
    description: 'Statistical significance vs. fold change.',
  },
  {
    value: 'diffbind_plot_heatmap_group',
    label: 'Heatmap (Group)',
    description: 'Correlation heatmap grouped by sample similarity.',
  },
  {
    value: 'diffbind_plot_heatmap_condition',
    label: 'Heatmap (Condition)',
    description: 'Binding affinity heatmap colored by condition.',
  },
  {
    value: 'diffbind_sample_sheet',
    label: 'Sample Sheet',
    description: 'The DiffBind sample sheet CSV used for the analysis.',
  },
  {
    value: 'log',
    label: 'Logs',
    description: 'DiffBind pipeline execution log files.',
  },
] as const;

export const CUSTOM_HEATMAP_FILE_CATEGORIES = [
  {
    value: 'custom_heatmap_plot',
    label: 'Heatmap Plot',
    description:
      'Reference-point heatmap generated by deepTools plotHeatmap (PNG + SVG).',
  },
  {
    value: 'custom_heatmap_profile',
    label: 'Profile Plot',
    description:
      'Mean signal profile plot generated by deepTools plotProfile (PNG + SVG).',
  },
  {
    value: 'custom_heatmap_matrix',
    label: 'Matrix',
    description:
      'deepTools computeMatrix output (.gz) for recomputation or custom plotting.',
  },
  {
    value: 'custom_heatmap_bed',
    label: 'Reference BED',
    description:
      'The BED file of reference points used for this heatmap.',
  },
  {
    value: 'log',
    label: 'Logs',
    description: 'Custom heatmap pipeline execution log files.',
  },
] as const;

export const PEARSON_CORRELATION_FILE_CATEGORIES = [
  {
    value: 'pearson_heatmap',
    label: 'Correlation Heatmap',
    description: 'Pairwise Pearson correlation heatmap (PNG + SVG).',
  },
  {
    value: 'pearson_matrix',
    label: 'Coverage Matrix',
    description: 'Raw coverage matrix at 50bp resolution across all genomic bins (CSV).',
  },
  {
    value: 'pearson_correlation',
    label: 'Correlation Matrix',
    description: 'Pairwise Pearson correlation coefficients between all samples (CSV).',
  },
  {
    value: 'pearson_sample_sheet',
    label: 'Sample Sheet',
    description: 'The sample sheet CSV used for the analysis.',
  },
  {
    value: 'log',
    label: 'Logs',
    description: 'Pipeline execution log files.',
  },
] as const;

export const NORMALIZATION_FILE_CATEGORIES = [
  {
    value: 'normalization_bigwig',
    label: 'Normalized bigWig',
    description: 'Per-sample Roman-normalized bigWig files for IGV visualization.',
  },
  {
    value: 'normalization_factors',
    label: 'Normalization Factors',
    description: '99th percentile values and normalization factors for each sample (CSV).',
  },
  {
    value: 'normalization_plot',
    label: 'Normalization Plot',
    description: 'Bar chart visualization of normalization factors (PNG + SVG).',
  },
  {
    value: 'normalization_sample_sheet',
    label: 'Sample Sheet',
    description: 'The sample sheet CSV used for the analysis.',
  },
  {
    value: 'log',
    label: 'Logs',
    description: 'Pipeline execution log files.',
  },
] as const;

export const TRIMMING_FILE_CATEGORIES = [
  {
    value: 'trimmed_fastq',
    label: 'Trimmed FASTQs',
    description: 'Adapter-trimmed and fixed-length (42bp) paired-end FASTQ files.',
  },
] as const;

export const RNASEQ_TRIMMING_FILE_CATEGORIES = [
  {
    value: 'trimmed_fastq',
    label: 'Trimmed FASTQs',
    description: 'Adapter-trimmed and quality-filtered paired-end FASTQ files produced by fastp.',
  },
  {
    value: 'fastp_html',
    label: 'fastp HTML Reports',
    description: 'Interactive HTML quality reports generated by fastp for each sample pair.',
  },
  {
    value: 'fastp_json',
    label: 'fastp JSON Reports',
    description: 'Machine-readable JSON reports with detailed trimming statistics from fastp.',
  },
] as const;

export const RNASEQ_ALIGNMENT_FILE_CATEGORIES = [
  {
    value: 'sorted_bam',
    label: 'Sorted BAM',
    description: 'Coordinate-sorted BAM files from STAR alignment, indexed with samtools.',
  },
  {
    value: 'bam_index',
    label: 'BAM Index',
    description: 'BAI index files for the sorted BAM files.',
  },
  {
    value: 'transcriptome_bam',
    label: 'Transcriptome BAM',
    description: 'STAR TranscriptomeSAM output BAMs for downstream Salmon/RSEM quantification.',
  },
  {
    value: 'bigwig',
    label: 'bigWig',
    description: 'RPKM-normalized signal tracks with bin size 20, suitable for precise downstream analyses.',
  },
  {
    value: 'smoothed_bigwig',
    label: 'Smoothed bigWig',
    description: 'Smoothed RPKM-normalized signal tracks with bin size 100, optimized for IGV visualization.',
  },
  {
    value: 'salmon_quant',
    label: 'Salmon Quantification',
    description: 'Salmon quant.sf files containing transcript-level TPM and estimated counts.',
  },
  {
    value: 'star_log',
    label: 'STAR Logs',
    description: 'STAR alignment log files including Log.final.out with mapping statistics.',
  },
  {
    value: 'qc_report',
    label: 'QC Report',
    description: 'Alignment QC metrics CSV with STAR and Salmon statistics per reaction.',
  },
  {
    value: 'master_log',
    label: 'Pipeline Log',
    description: 'Master pipeline execution log with timestamps for all processing steps.',
  },
] as const;

export const RNASEQ_REFERENCE_GENOMES: Record<string, { value: string; label: string }[]> = {
  Human: [{ value: 'hg38', label: 'Human GRCh38/hg38' }],
  Mouse: [{ value: 'mm10', label: 'Mouse mm10' }],
};

export const RNASEQ_FEATURE_COUNTS_FILE_CATEGORIES = [
  {
    value: 'count_matrix',
    label: 'Count Matrix',
    description: 'Gene-level read counts (genes x samples) produced by featureCounts.',
  },
  {
    value: 'count_summary',
    label: 'Assignment Summary',
    description: 'featureCounts read assignment statistics (assigned, unassigned, ambiguous).',
  },
  {
    value: 'master_log',
    label: 'Pipeline Log',
    description: 'Execution log with timestamps.',
  },
] as const;

export const RNASEQ_DE_FILE_CATEGORIES = [
  {
    value: 'de_results',
    label: 'DE Results',
    description: 'Full DESeq2 results table with gene names, fold changes, p-values, and FDR.',
  },
  {
    value: 'normalized_counts',
    label: 'Normalized Counts',
    description: 'DESeq2-normalized read counts matrix (genes x samples).',
  },
  {
    value: 'volcano_plot',
    label: 'Volcano Plot',
    description: 'Log2 fold change vs. -log10(adjusted p-value) with labeled top hits.',
  },
  {
    value: 'ma_plot',
    label: 'MA Plot',
    description: 'Log2 fold change vs. mean normalized counts (DESeq2 plotMA).',
  },
  {
    value: 'pca_plot',
    label: 'PCA Plot',
    description: 'Principal component analysis of regularized log-transformed counts.',
  },
  {
    value: 'distance_heatmap',
    label: 'Sample Distance Heatmap',
    description: 'Euclidean distance heatmap between all samples.',
  },
  {
    value: 'gene_heatmap',
    label: 'Top Genes Heatmap',
    description: 'Heatmap of top 50 differentially expressed genes by adjusted p-value.',
  },
  {
    value: 'de_sample_sheet',
    label: 'Sample Sheet',
    description: 'The sample metadata CSV used for the DESeq2 analysis.',
  },
  {
    value: 'log',
    label: 'Logs',
    description: 'Pipeline execution log files.',
  },
] as const;

export const RNASEQ_DE_QUANTIFICATION_SOURCES = [
  { value: 'salmon', label: 'Salmon (tximport)' },
  { value: 'featurecounts', label: 'featureCounts' },
] as const;

export const SALMON_LIB_TYPE_TO_STRANDEDNESS: Record<string, number> = {
  ISR: 2,
  SR: 2,
  ISF: 1,
  SF: 1,
  IU: 0,
  U: 0,
};

export const STRANDEDNESS_OPTIONS = [
  { value: 0, label: '0 — Unstranded' },
  { value: 1, label: '1 — Forward (sense)' },
  { value: 2, label: '2 — Reverse (antisense)' },
] as const;

export const HEATMAP_SORT_ORDERS = [
  { value: 'descend', label: 'Descending (default)' },
  { value: 'ascend', label: 'Ascending' },
  { value: 'no', label: 'No sorting' },
  { value: 'keep', label: 'Keep input order' },
] as const;

export const HEATMAP_COLOR_MAPS = [
  { value: '', label: 'Default (deepTools)' },
  { value: 'RdYlBu_r', label: 'Red-Yellow-Blue (reversed)' },
  { value: 'viridis', label: 'Viridis' },
  { value: 'Reds', label: 'Reds' },
  { value: 'Blues', label: 'Blues' },
  { value: 'YlOrRd', label: 'Yellow-Orange-Red' },
  { value: 'hot', label: 'Hot' },
] as const;

export const HEATMAP_REFERENCE_POINTS = [
  { value: 'center', label: 'Center (lab default)' },
  { value: 'TSS', label: 'TSS' },
  { value: 'TES', label: 'TES' },
] as const;

export const CUTANA_SPIKE_IN_TARGETS = [
  'Unmodified',
  'H3K4me1',
  'H3K4me2',
  'H3K4me3',
  'H3K9me1',
  'H3K9me2',
  'H3K9me3',
  'H3K27me1',
  'H3K27me2',
  'H3K27me3',
  'H3K36me1',
  'H3K36me2',
  'H3K36me3',
  'H4K20me1',
  'H4K20me2',
  'H4K20me3',
] as const;
