// frontend/src/lib/constants.ts

export const STATUS_COLORS: Record<string, string> = {
  new: 'bg-status-new',
  in_progress: 'bg-status-in-progress',
  complete: 'bg-status-complete',
  error: 'bg-status-error',
  terminated: 'bg-status-terminated',
  queued: 'bg-status-new',
  running: 'bg-status-in-progress',
};

export const STATUS_LABELS: Record<string, string> = {
  new: 'New',
  in_progress: 'In Progress',
  complete: 'Complete',
  error: 'Error',
  terminated: 'Terminated',
  queued: 'Queued',
  running: 'Running',
};

export const ROLE_LABELS: Record<string, string> = {
  admin: 'Admin',
  contributor: 'Contributor',
  viewer: 'Viewer',
};

export const EMAIL_NOTIFICATION_OPTIONS = [
  { value: 'always', label: 'Always' },
  { value: 'on_error', label: 'On Error' },
  { value: 'never', label: 'Never' },
] as const;

export const ASSAY_TYPES = ['CUT&RUN', 'CUT&Tag'] as const;

export const ORGANISMS = ['Human', 'Mouse', 'Drosophila', 'Yeast'] as const;

export const CUTANA_SPIKE_IN_OPTIONS = ['None', 'KMetStat'] as const;

export const REFERENCE_GENOMES: Record<string, { value: string; label: string }[]> = {
  Human: [
    { value: 'hg38', label: 'Human GRCh38/hg38' },
    { value: 'hg19', label: 'Human hg19' },
  ],
  Mouse: [{ value: 'mm10', label: 'Mouse mm10' }],
  Drosophila: [{ value: 'dm6', label: 'Drosophila dm6' }],
  Yeast: [{ value: 'sacCer3', label: 'Yeast sacCer3' }],
};

export const GENOME_DISPLAY_NAMES: Record<string, string> = {
  mm10: 'Mouse mm10',
  hg38: 'Human GRCh38/hg38',
  hg19: 'Human hg19',
  dm6: 'Drosophila dm6',
  sacCer3: 'Yeast sacCer3',
};

export const ALIGNMENT_FILE_CATEGORIES = [
  {
    value: 'unique_bam',
    label: 'Unique BAM',
    description:
      'A BAM file is a compressed output from Alignment representing each sequencing read and where they align to the reference genome. The Unique BAM is the final version that has been filtered for reads that align to multiple locations on the genome, are duplicates, or map to DAC Exclusion List Regions.',
  },
  {
    value: 'bigwig',
    label: 'bigWig',
    description:
      'RPKM-normalized signal tracks with binsize 20, used for precise heatmap generation without artificial smoothing.',
  },
  {
    value: 'smoothed_bigwig',
    label: 'smoothed bigWig',
    description:
      'Smoothed RPKM-normalized signal tracks with binsize 100, optimized for visual clarity when exploring data in IGV.',
  },
  {
    value: 'tss_heatmap',
    label: 'TSS Heatmaps',
    description:
      'Heatmap images showing enrichment of unique reads around transcription start sites, generated by deepTools plotHeatmap.',
  },
  {
    value: 'genebody_heatmap',
    label: 'Gene Body Heatmaps',
    description:
      'Heatmap images showing enrichment of unique reads across scaled gene bodies, generated by deepTools plotHeatmap.',
  },
  {
    value: 'log',
    label: 'Logs',
    description:
      'Pipeline execution log files including Bowtie2 alignment logs and Picard duplicate marking metrics.',
  },
] as const;

export const CUTANA_SPIKE_IN_TARGETS = [
  'Unmodified',
  'H3K4me1',
  'H3K4me2',
  'H3K4me3',
  'H3K9me1',
  'H3K9me2',
  'H3K9me3',
  'H3K27me1',
  'H3K27me2',
  'H3K27me3',
  'H3K36me1',
  'H3K36me2',
  'H3K36me3',
  'H4K20me1',
  'H4K20me2',
  'H4K20me3',
] as const;
